clear all

set maxvar 10000


* 2023
use "pu2023.dta", clear

keep SHHADID SPANEL SSUID SWAVE PNUM MONTHCODE WPFINWGT TAGE EEDUC ESEX ERACE TMETRO_INTV EJB1_JBORSE EJB1_CLWRK TPTOTINC EMJOB_401 EMJOB_IRA EMJOB_PEN EOWN_THR401 EOWN_IRAKEO EOWN_PENSION ESCNTYN_401 EECNTYN_401 EORIGIN TJB1_JOBHRS1 ESCNTYN_PEN ESCNTYN_IRA EECNTYN_IRA TVAL_RET
	

export delimited  "pu2023.csv", replace
